const fs = require("fs");
const lines = [];

lines.push("import { describe, expect, it } from 'vitest';");
lines.push('');
lines.push('import {');
lines.push('  MemoryConfigError,');
lines.push('  MemoryOperationError,');
lines.push('  MemoryQueryError,');
lines.push("} from '../../../src/errors/memory-errors.js';");
lines.push('');
lines.push("describe('MemoryConfigError', () => {");
lines.push("  it('formats message without provider', () => {");
lines.push("    const err = new MemoryConfigError('bad config');");
lines.push("    expect(err.message).toBe('bad config');");
lines.push("    expect(err.name).toBe('MemoryConfigError');");
lines.push('    expect(err.provider).toBeUndefined();');
lines.push('  });');
lines.push('');
lines.push("  it('formats message with provider', () => {");
lines.push("    const err = new MemoryConfigError('bad config', 'sqlite');");
lines.push("    expect(err.message).toContain('sqlite');");
lines.push("    expect(err.message).toContain('bad config');");
lines.push("    expect(err.provider).toBe('sqlite');");
lines.push('  });');
lines.push('');
lines.push("  it('is an instance of Error', () => {");
lines.push("    expect(new MemoryConfigError('x')).toBeInstanceOf(Error);");
lines.push('  });');
lines.push('});');
lines.push('');
lines.push("describe('MemoryOperationError', () => {");
lines.push("  it('formats message correctly', () => {");
lines.push("    const err = new MemoryOperationError('short-term', 'add', 'duplicate id');");
lines.push("    expect(err.message).toContain('short-term');");
lines.push("    expect(err.message).toContain('add');");
lines.push("    expect(err.message).toContain('duplicate id');");
lines.push("    expect(err.name).toBe('MemoryOperationError');");
lines.push("    expect(err.provider).toBe('short-term');");
lines.push("    expect(err.operation).toBe('add');");
lines.push('    expect(err.cause).toBeUndefined();');
lines.push('  });');
lines.push('');
lines.push("  it('includes cause when provided', () => {");
lines.push("    const cause = new Error('root cause');");
lines.push("    const err = new MemoryOperationError('sqlite', 'query', 'failed', cause);");
lines.push('    expect(err.cause).toBe(cause);');
lines.push('  });');
lines.push('');
lines.push("  it('is an instance of Error', () => {");
lines.push("    expect(new MemoryOperationError('p', 'op', 'm')).toBeInstanceOf(Error);");
lines.push('  });');
lines.push('});');
lines.push('');
lines.push("describe('MemoryQueryError', () => {");
lines.push("  it('formats message correctly', () => {");
lines.push("    const err = new MemoryQueryError('short-term', 'invalid filter');");
lines.push("    expect(err.message).toContain('short-term');");
lines.push("    expect(err.message).toContain('invalid filter');");
lines.push("    expect(err.name).toBe('MemoryQueryError');");
lines.push("    expect(err.provider).toBe('short-term');");
lines.push('  });');
lines.push('');
lines.push("  it('is an instance of Error', () => {");
lines.push("    expect(new MemoryQueryError('p', 'm')).toBeInstanceOf(Error);");
lines.push('  });');
lines.push('});');
lines.push('');

fs.writeFileSync("packages/core/tests/unit/memory/memory-errors.test.ts", lines.join('\n'));
console.log('wrote memory-errors.test.ts');