const fs = require('fs');
const lines = [];

lines.push("import { describe, expect, it } from 'vitest';");
lines.push('');
lines.push("import { MemoryNamespace, MemoryRole } from '../../../src/types/memory.js';");
lines.push('import type {');
lines.push('  MemoryConfig,');
lines.push('  MemoryEntry,');
lines.push('  MemoryMetadata,');
lines.push('  MemoryQueryResult,');
lines.push('  MemoryRetentionPolicy,');
lines.push("} from '../../../src/types/memory.js';");
lines.push('');
lines.push("describe('MemoryNamespace enum', () => {");
lines.push("  it('has AGENT, CREW, GLOBAL values', () => {");
lines.push("    expect(MemoryNamespace.AGENT).toBe('agent');");
lines.push("    expect(MemoryNamespace.CREW).toBe('crew');");
lines.push("    expect(MemoryNamespace.GLOBAL).toBe('global');");
lines.push('  });');
lines.push('});');
lines.push('');
lines.push("describe('MemoryRole enum', () => {");
lines.push("  it('has USER, ASSISTANT, SYSTEM, TOOL values', () => {");
lines.push("    expect(MemoryRole.USER).toBe('user');");
lines.push("    expect(MemoryRole.ASSISTANT).toBe('assistant');");
lines.push("    expect(MemoryRole.SYSTEM).toBe('system');");
lines.push("    expect(MemoryRole.TOOL).toBe('tool');");
lines.push('  });');
lines.push('});');
lines.push('');
lines.push("describe('Type contracts', () => {");
lines.push("  it('MemoryEntry satisfies the interface', () => {");
lines.push('    const entry: MemoryEntry = {');
lines.push("      id: 'test',");
lines.push("      content: 'hello',");
lines.push('      role: MemoryRole.USER,');
lines.push('      namespace: MemoryNamespace.AGENT,');
lines.push('      createdAt: new Date().toISOString(),');
lines.push('    };');
lines.push("    expect(entry.id).toBe('test');");
lines.push('  });');
lines.push('');
lines.push("  it('MemoryEntry with metadata', () => {");
lines.push("    const metadata: MemoryMetadata = { agentId: 'a1', score: 0.95, important: true };");
lines.push('    const entry: MemoryEntry = {');
lines.push("      id: 'test2',");
lines.push("      content: 'data',");
lines.push('      role: MemoryRole.ASSISTANT,');
lines.push('      namespace: MemoryNamespace.CREW,');
lines.push('      createdAt: new Date().toISOString(),');
lines.push('      metadata,');
lines.push('    };');
lines.push("    expect(entry.metadata?.agentId).toBe('a1');");
lines.push('  });');
lines.push('');
lines.push("  it('MemoryConfig satisfies the interface', () => {");
lines.push('    const config: MemoryConfig = {');
lines.push('      defaultNamespace: MemoryNamespace.CREW,');
lines.push('      retention: { maxEntries: 100, maxAge: 3600_000 },');
lines.push('    };');
lines.push('    expect(config.retention?.maxEntries).toBe(100);');
lines.push('  });');
lines.push('');
lines.push("  it('MemoryRetentionPolicy satisfies the interface', () => {");
lines.push('    const policy: MemoryRetentionPolicy = { maxEntries: 50, maxAge: 0 };');
lines.push('    expect(policy.maxEntries).toBe(50);');
lines.push('  });');
lines.push('');
lines.push("  it('MemoryQueryResult satisfies the interface', () => {");
lines.push('    const result: MemoryQueryResult = { entries: [], total: 0 };');
lines.push('    expect(result.total).toBe(0);');
lines.push('  });');
lines.push('});');
lines.push('');

fs.writeFileSync('packages/core/tests/unit/memory/memory-types.test.ts', lines.join('\n'));
console.log('wrote memory-types.test.ts');