const fs = require("fs");
const lines = [];

lines.push('/**');
lines.push(' * Memory manager - coordinates one or more MemoryProviders.');
lines.push(' *');
lines.push(' * @packageDocumentation');
lines.push(' */');
lines.push('');
lines.push("import { EventEmitter } from 'eventemitter3';");
lines.push('');
lines.push("import { MemoryConfigError, MemoryOperationError } from '../errors/memory-errors.js';");
lines.push('import type {');
lines.push('  MemoryConfig,');
lines.push('  MemoryEntry,');
lines.push('  MemoryEventMap,');
lines.push('  MemoryProvider,');
lines.push('  MemoryQueryOptions,');
lines.push('  MemoryQueryResult,');
lines.push("} from '../types/memory.js';");
lines.push("import { MemoryNamespace, MemoryRole } from '../types/memory.js';");
lines.push('');
lines.push('let _counter = 0;');
lines.push('');
lines.push('/** Generate a simple unique id. */');
lines.push('export function generateMemoryId(): string {');
lines.push('  _counter++;');
lines.push('  const timestamp = Date.now().toString(36);');
lines.push('  const random = Math.random().toString(36).slice(2, 8);');
lines.push('  return `mem_${timestamp}_${random}_${String(_counter)}`;');
lines.push('}');
lines.push('');
lines.push('/** Create a fully-populated MemoryEntry with auto-generated id. */');
lines.push('export function createMemoryEntry(');
lines.push('  content: string,');
lines.push('  role: MemoryRole,');
lines.push('  namespace: MemoryNamespace = MemoryNamespace.AGENT,');
lines.push("  metadata?: MemoryEntry['metadata'],");
lines.push('): MemoryEntry {');
lines.push('  return Object.freeze({');
lines.push('    id: generateMemoryId(),');
lines.push('    content,');
lines.push('    role,');
lines.push('    namespace,');
lines.push('    createdAt: new Date().toISOString(),');
lines.push('    ...(metadata !== undefined && { metadata }),');
lines.push('  });');
lines.push('}');
lines.push('');
lines.push('/** Configuration for MemoryManager. */');
lines.push('export interface MemoryManagerConfig extends MemoryConfig {');
lines.push('  readonly providers?: readonly MemoryProvider[];');
lines.push('}');
lines.push('');
lines.push('/** Coordinates multiple memory providers behind a single interface. */');
lines.push('export class MemoryManager implements MemoryProvider {');
lines.push("  public readonly name = 'manager';");
lines.push('');
lines.push('  private readonly _providers: MemoryProvider[];');
lines.push('  private readonly _defaultNamespace: MemoryNamespace;');
lines.push('  private readonly _emitter: EventEmitter<MemoryEventMap>;');
lines.push('');
lines.push('  constructor(config?: MemoryManagerConfig) {');
lines.push('    this._emitter = new EventEmitter<MemoryEventMap>();');
lines.push('    this._defaultNamespace = config?.defaultNamespace ?? MemoryNamespace.AGENT;');
lines.push('    this._providers = config?.providers ? [...config.providers] : [];');
lines.push('');
lines.push('    const names = new Set<string>();');
lines.push('    for (const p of this._providers) {');
lines.push('      if (names.has(p.name)) {');
lines.push('        throw new MemoryConfigError(');
lines.push('          `Duplicate provider name "${p.name}"`,');
lines.push("          'manager',");
lines.push('        );');
lines.push('      }');
lines.push('      names.add(p.name);');
lines.push('    }');
lines.push('  }');
lines.push('');
lines.push('  /** The default namespace for entries. */');
lines.push('  get defaultNamespace(): MemoryNamespace {');
lines.push('    return this._defaultNamespace;');
lines.push('  }');
lines.push('');
lines.push('  /** Registered providers (read-only snapshot). */');
lines.push('  get providers(): readonly MemoryProvider[] {');
lines.push('    return [...this._providers];');
lines.push('  }');
lines.push('');
lines.push('  /** Register a new memory provider. */');
lines.push('  addProvider(provider: MemoryProvider): void {');
lines.push('    if (this._providers.some((p) => p.name === provider.name)) {');
lines.push('      throw new MemoryConfigError(');
lines.push('        `Provider "${provider.name}" is already registered`,');
lines.push("        'manager',");
lines.push('      );');
lines.push('    }');
lines.push('    this._providers.push(provider);');
lines.push('  }');
lines.push('');
lines.push('  /** Remove a provider by name. */');
lines.push('  removeProvider(name: string): boolean {');
lines.push('    const idx = this._providers.findIndex((p) => p.name === name);');
lines.push('    if (idx === -1) return false;');
lines.push('    this._providers.splice(idx, 1);');
lines.push('    return true;');
lines.push('  }');
lines.push('');
lines.push('  /** Get a provider by name. */');
lines.push('  getProvider(name: string): MemoryProvider | undefined {');
lines.push('    return this._providers.find((p) => p.name === name);');
lines.push('  }');
lines.push('');
lines.push('  on<E extends keyof MemoryEventMap>(event: E, listener: MemoryEventMap[E]): this {');
lines.push('    this._emitter.on(event, listener as (...args: unknown[]) => void);');
lines.push('    return this;');
lines.push('  }');
lines.push('');
lines.push('  off<E extends keyof MemoryEventMap>(event: E, listener: MemoryEventMap[E]): this {');
lines.push('    this._emitter.off(event, listener as (...args: unknown[]) => void);');
lines.push('    return this;');
lines.push('  }');
lines.push('');
lines.push('  async add(entry: MemoryEntry): Promise<MemoryEntry> {');
lines.push("    this._ensureProviders('add');");
lines.push('    let stored: MemoryEntry = entry;');
lines.push('    const errors: Error[] = [];');
lines.push('    for (const provider of this._providers) {');
lines.push('      try {');
lines.push('        stored = await provider.add(entry);');
lines.push('      } catch (err) {');
lines.push('        errors.push(err instanceof Error ? err : new Error(String(err)));');
lines.push('      }');
lines.push('    }');
lines.push('    if (errors.length === this._providers.length) {');
lines.push('      throw new MemoryOperationError(');
lines.push('        this.name,');
lines.push("        'add',");
lines.push("        `All providers failed: ${errors.map((e) => e.message).join('; ')}`,");
lines.push('      );');
lines.push('    }');
lines.push("    this._emit('memory:add', stored);");
lines.push('    return stored;');
lines.push('  }');
lines.push('');
lines.push('  async get(id: string): Promise<MemoryEntry | undefined> {');
lines.push('    for (const provider of this._providers) {');
lines.push('      const entry = await provider.get(id);');
lines.push('      if (entry) return entry;');
lines.push('    }');
lines.push('    return undefined;');
lines.push('  }');
lines.push('');
lines.push('  async query(options?: MemoryQueryOptions): Promise<MemoryQueryResult> {');
lines.push('    if (this._providers.length === 0) return { entries: [], total: 0 };');
lines.push('    const primary = this._providers[0];');
lines.push('    if (!primary) return { entries: [], total: 0 };');
lines.push('    return primary.query(options);');
lines.push('  }');
lines.push('');
lines.push('  async search(text: string, options?: MemoryQueryOptions): Promise<MemoryQueryResult> {');
lines.push('    if (this._providers.length === 0) return { entries: [], total: 0 };');
lines.push('    const primary = this._providers[0];');
lines.push('    if (!primary) return { entries: [], total: 0 };');
lines.push('    return primary.search(text, options);');
lines.push('  }');
lines.push('');
lines.push('  async delete(id: string): Promise<boolean> {');
lines.push('    let deleted = false;');
lines.push('    for (const provider of this._providers) {');
lines.push('      const result = await provider.delete(id);');
lines.push('      if (result) deleted = true;');
lines.push('    }');
lines.push("    if (deleted) this._emit('memory:delete', id);");
lines.push('    return deleted;');
lines.push('  }');
lines.push('');
lines.push('  async clear(namespace?: MemoryNamespace): Promise<number> {');
lines.push('    let total = 0;');
lines.push('    for (const provider of this._providers) {');
lines.push('      total += await provider.clear(namespace);');
lines.push('    }');
lines.push("    this._emit('memory:clear', namespace, total);");
lines.push('    return total;');
lines.push('  }');
lines.push('');
lines.push('  async count(namespace?: MemoryNamespace): Promise<number> {');
lines.push('    if (this._providers.length === 0) return 0;');
lines.push('    const primary = this._providers[0];');
lines.push('    if (!primary) return 0;');
lines.push('    return primary.count(namespace);');
lines.push('  }');
lines.push('');
lines.push('  private _ensureProviders(operation: string): void {');
lines.push('    if (this._providers.length === 0) {');
lines.push('      throw new MemoryOperationError(');
lines.push('        this.name,');
lines.push('        operation,');
lines.push("        'No memory providers registered. Call addProvider() first.',");
lines.push('      );');
lines.push('    }');
lines.push('  }');
lines.push('');
lines.push('  private _emit<E extends keyof MemoryEventMap>(');
lines.push('    event: E,');
lines.push('    ...args: Parameters<MemoryEventMap[E]>');
lines.push('  ): void {');
lines.push('    // eslint-disable-next-line @typescript-eslint/no-explicit-any');
lines.push('    (this._emitter.emit as (event: string, ...args: any[]) => boolean)(event, ...args);');
lines.push('  }');
lines.push('}');
lines.push('');

fs.writeFileSync("packages/core/src/memory/memory-manager.ts", lines.join('\n'));
console.log('wrote memory-manager.ts:', lines.length, 'lines');