/**
 * @crewspace/ui — Design system React components
 *
 * This package provides the Crewspace visual design system:
 * - Tailwind theme preset & CSS custom properties
 * - Base UI components (Button, Input, Card, Badge, Modal, Tooltip, Spinner)
 * - Responsive layout system (ResponsiveLayout, hooks)
 * - Design token constants for programmatic access
 */

// Components
export {
  Button,
  type ButtonProps,
  type ButtonVariant,
  type ButtonSize,
  Input,
  type InputProps,
  // Form Validation (TASK-187)
  FormField,
  type FormFieldProps,
  type ValidationState,
  Textarea,
  type TextareaProps,
  required,
  minLength,
  maxLength,
  maxLengthWarning,
  pattern,
  email,
  showValid,
  Card,
  CardHeader,
  CardBody,
  type CardProps,
  type CardHeaderProps,
  type CardBodyProps,
  Badge,
  type BadgeProps,
  type BadgeVariant,
  Modal,
  type ModalProps,
  Tooltip,
  type TooltipProps,
  Spinner,
  type SpinnerProps,
  // Error Handling (TASK-181)
  ErrorBoundary,
  type ErrorBoundaryProps,
  type ErrorBoundaryState,
  ErrorFallback,
  type ErrorFallbackProps,
  type ErrorSeverity,
  // Layout (TASK-172)
  ResponsiveLayout,
  type ResponsiveLayoutProps,
  type SidebarMode,
  // Canvas (TASK-135, TASK-136, TASK-137)
  WorkflowCanvas,
  type WorkflowCanvasProps,
  WorkflowNode,
  WorkflowEdge,
  CanvasBackground,
  type CanvasBackgroundProps,
  CanvasControls,
  type CanvasControlsProps,
  CanvasMinimap,
  type CanvasMinimapProps,
  NodeShell,
  type NodeShellProps,
  defaultIcons,
  AgentNode,
  TaskNode,
  ToolNode,
  LLMNode,
  // TASK-137: Toolbar & Properties Panel
  CanvasToolbar,
  type CanvasToolbarProps,
  type ToolbarNodeEntry,
  DEFAULT_NODE_ENTRIES,
  PropertiesPanel,
  type PropertiesPanelProps,
  type CanvasNodeType,
  type NodeStatus,
  type WorkflowNodeData,
  type EdgeVariant,
  type WorkflowEdgeData,
  type BaseNodeProps,
  type AgentNodeMeta,
  type TaskNodeMeta,
  type ToolNodeMeta,
  type LLMNodeMeta,
  type NodeStyleOverrides,
  Z_INDEX,
  CANVAS_CONFIG,
  // Timeline (TASK-143)
  TimelineChart,
  type TimelineChartProps,
  TimeAxis,
  type TimeAxisProps,
  AgentLane,
  type AgentLaneProps,
  EventBlock,
  type EventBlockProps,
  EventMarker,
  type EventMarkerProps,
  Playhead,
  type PlayheadProps,
  // Playback (TASK-146)
  PlaybackControls,
  type PlaybackControlsProps,
  TimelinePlayer,
  type TimelinePlayerProps,
  formatPlaybackTime,
  type PlaybackSpeed,
  type PlaybackStatus,
  type PlaybackState,
  TIMELINE_SIZING,
  EVENT_STYLES,
  isPointEvent,
  type TimelineEventType,
  type LogLevel,
  type TimelineEvent,
  type TimelineAgent,
  type TimelineViewport,
  type TickScale,
  // Log Viewer (TASK-144)
  LogViewer,
  type LogViewerProps,
  LogRow,
  type LogRowProps,
  type LogEntry,
  formatTimestamp,
  tokenizeJson,
  highlightSearch,
  type SyntaxToken,
  type HighlightSegment,
  LOG_SIZING,
  LOG_LEVEL_STYLES,
  LOG_COLORS,
  SYNTAX_COLORS,
  // Log Filters (TASK-145)
  LogFilterBar,
  type LogFilterBarProps,
  type LogFilters,
  type LogFilterOption,
  filterLogEntries,
  DEFAULT_LOG_FILTERS,
  // Template Browser (TASK-159)
  TemplateCategoryBadge,
  type TemplateCategoryBadgeProps,
  TemplateTag,
  type TemplateTagProps,
  FeaturedBadge,
  type FeaturedBadgeProps,
  TemplateCard,
  type TemplateCardProps,
  TemplateSearchBar,
  type TemplateSearchBarProps,
  TemplateCategoryFilter,
  type TemplateCategoryFilterProps,
  TemplateSortDropdown,
  type TemplateSortDropdownProps,
  TemplateToolbar,
  type TemplateToolbarProps,
  TemplateGrid,
  type TemplateGridProps,
  TemplateEmptyState,
  type TemplateEmptyStateProps,
  TemplatePagination,
  type TemplatePaginationProps,
  TemplateBrowserPage,
  type TemplateBrowserPageProps,
  // Template Preview (TASK-160)
  TemplatePreviewModal,
  type TemplatePreviewModalProps,
  WorkflowDiagram,
  type WorkflowDiagramProps,
  type WorkflowDiagramNode,
  type WorkflowDiagramEdge,
  // Template Instantiation (TASK-161)
  UseTemplateDialog,
  type UseTemplateDialogProps,
  TemplateBrowserWithInstantiation,
  type TemplateBrowserWithInstantiationProps,
  type TemplateCategory,
  type TemplateSortField,
  type TemplateSortDirection,
  type TemplateSummary,
  type TemplateFilters,
  TEMPLATE_CATEGORIES,
  SORT_OPTIONS,
  ITEMS_PER_PAGE,
  // Usage Stats (TASK-152)
  PlanBadge,
  type PlanBadgeProps,
  UsageProgressBar,
  type UsageProgressBarProps,
  UsageStatCard,
  type UsageStatCardProps,
  UsageLimitAlert,
  type UsageLimitAlertProps,
  UpgradePrompt,
  type UpgradePromptProps,
  UsageStatsPanel,
  type UsageStatsPanelProps,
  type PlanTier,
  type PlanLimits,
  type UsageStats,
  type UsageAlertSeverity,
  isUnlimited,
  PLAN_DISPLAY_NAMES,
  USAGE_THRESHOLDS,
  getAlertSeverity,
  // Dashboard (TASK-151)
  WorkflowStatusBadge,
  type WorkflowStatusBadgeProps,
  WorkflowCard,
  type WorkflowCardProps,
  WorkflowListRow,
  type WorkflowListRowProps,
  SearchBar,
  type SearchBarProps,
  FilterChips,
  type FilterChipsProps,
  type FilterOption,
  ViewToggle,
  type ViewToggleProps,
  DashboardToolbar,
  type DashboardToolbarProps,
  EmptyState,
  type EmptyStateProps,
  WorkflowGrid,
  type WorkflowGridProps,
  WorkflowList,
  type WorkflowListProps,
  DashboardPage,
  type DashboardPageProps,
  type WorkflowStatus,
  type ViewMode,
  type SortField,
  type SortDirection,
  type WorkflowSummary,
  type DashboardFilters,
  // Marketplace Browser (TASK-166)
  IntegrationCategoryBadge,
  type IntegrationCategoryBadgeProps,
  VerifiedBadge,
  type VerifiedBadgeProps,
  StarRating,
  type StarRatingProps,
  IntegrationCard,
  type IntegrationCardProps,
  IntegrationGrid,
  type IntegrationGridProps,
  MarketplaceSearchBar,
  type MarketplaceSearchBarProps,
  MarketplaceCategoryFilter,
  type MarketplaceCategoryFilterProps,
  MarketplaceSortDropdown,
  type MarketplaceSortDropdownProps,
  MarketplaceToolbar,
  type MarketplaceToolbarProps,
  MarketplaceEmptyState,
  type MarketplaceEmptyStateProps,
  MarketplacePagination,
  type MarketplacePaginationProps,
  MarketplaceBrowserPage,
  type MarketplaceBrowserPageProps,
  type IntegrationCategory,
  type IntegrationSortField,
  type MarketplaceSortDirection,
  type IntegrationSummary,
  type MarketplaceFilters,
  INTEGRATION_CATEGORIES,
  MARKETPLACE_SORT_OPTIONS,
  MARKETPLACE_ITEMS_PER_PAGE,
  // OAuth Flows (TASK-167)
  OAuthStatusBadge,
  type OAuthStatusBadgeProps,
  OAuthProviderCard,
  type OAuthProviderCardProps,
  OAuthProviderList,
  type OAuthProviderListProps,
  OAuthConnectDialog,
  type OAuthConnectDialogProps,
  OAuthSettingsPanel,
  type OAuthSettingsPanelProps,
  type OAuthProvider,
  type OAuthConnectionStatus,
  type OAuthConnection,
  type OAuthFlowStatus,
  type OAuthProviderMeta,
  OAUTH_PROVIDERS,
  STATUS_LABELS,
  // Animations (TASK-173)
  FadeIn,
  type FadeInProps,
  SlideIn,
  type SlideInProps,
  type SlideDirection,
  ScaleIn,
  type ScaleInProps,
  PageTransition,
  type PageTransitionProps,
  AnimatePresence,
  type AnimatePresenceProps,
  Skeleton,
  type SkeletonProps,
  type SkeletonVariant,
  Shimmer,
  type ShimmerProps,
  PulseLoader,
  type PulseLoaderProps,
  StaggerList,
  type StaggerListProps,
  DURATION,
  EASING,
  STAGGER,
  type AnimationVariant,
  type AnimationPhase,
  type PageTransitionVariant,
  type LoadingVariant,
  // Accessibility (TASK-174)
  SkipLink,
  type SkipLinkProps,
  LiveRegion,
  type LiveRegionProps,
  type LiveRegionPoliteness,
  FocusScope,
  type FocusScopeProps,
  ShortcutHelpDialog,
  type ShortcutHelpDialogProps,
  // Feedback States (TASK-182)
  StatusEmpty,
  type StatusEmptyProps,
  StatusLoading,
  type StatusLoadingProps,
  StatusSuccess,
  type StatusSuccessProps,
  Toast,
  type ToastProps,
  ToastContainer,
  type ToastContainerProps,
  AsyncStateView,
  type AsyncStateViewProps,
  type FeedbackStatus,
  type ToastVariant,
  type ToastPosition,
  type ToastEntry,
  type AsyncState,
} from './components/index.js';

// Theme
export {
  crewspaceTailwindPreset,
  crewspaceTheme,
  responsiveTheme,
  mergedTheme,
} from './theme/index.js';

// Hooks (TASK-172)
export {
  useMediaQuery,
  useBreakpoint,
  BREAKPOINTS,
  type Breakpoint,
  type BreakpointState,
} from './hooks/index.js';

// Hooks — Async Error (TASK-181)
export {
  useAsyncError,
  type UseAsyncErrorOptions,
  type UseAsyncErrorResult,
  type AsyncStatus,
} from './hooks/index.js';

// Hooks — Canvas State (TASK-138)
export {
  useCanvasState,
  type UseCanvasStateOptions,
  type UseCanvasStateResult,
  type CanvasStateManager,
} from './hooks/index.js';

// Hooks — Log Filters (TASK-145)
export {
  useLogFilters,
  type UseLogFiltersOptions,
  type UseLogFiltersResult,
} from './hooks/index.js';

// Hooks — Timeline Playback (TASK-146)
export {
  useTimelinePlayback,
  PLAYBACK_SPEEDS,
  type UseTimelinePlaybackOptions,
  type UseTimelinePlaybackResult,
} from './hooks/index.js';

// Hooks — Template Instantiation (TASK-161)
export {
  useTemplateInstantiation,
  type UseTemplateInstantiationOptions,
  type UseTemplateInstantiationResult,
  type InstantiationStatus,
  type InstantiateFormValues,
  type InstantiationResult,
  type InstantiationTemplate,
} from './hooks/index.js';

// Hooks — OAuth Flow (TASK-167)
export { useOAuthFlow, type UseOAuthFlowOptions, type UseOAuthFlowResult } from './hooks/index.js';

// Hooks — Animation (TASK-173)
export { useAnimation, type UseAnimationOptions, type UseAnimationResult } from './hooks/index.js';

// Hooks — Accessibility (TASK-174)
export {
  useKeyboardShortcuts,
  formatShortcut,
  groupShortcutsByCategory,
  type KeyboardShortcut,
  type ModifierKey,
  type UseKeyboardShortcutsOptions,
  type UseKeyboardShortcutsResult,
} from './hooks/index.js';

export {
  useFocusTrap,
  getFocusableElements,
  type UseFocusTrapOptions,
  type UseFocusTrapResult,
} from './hooks/index.js';

export {
  useAriaAnnouncer,
  type AriaPoliteness,
  type UseAriaAnnouncerOptions,
  type UseAriaAnnouncerResult,
} from './hooks/index.js';

// Hooks — Toast (TASK-182)
export { useToast, type UseToastOptions, type UseToastResult } from './hooks/index.js';

// Hooks — Form Validation (TASK-187)
export {
  useFormValidation,
  type UseFormValidationOptions,
  type UseFormValidationResult,
  type FieldValidationResult,
  type FieldValidator,
  type FieldConfig,
  type FieldState,
} from './hooks/index.js';

// Design tokens (programmatic)
export {
  colors,
  sizing,
  radius,
  typography,
  transitions,
  breakpoints,
  responsive,
} from './theme/tokens.js';

// Performance (TASK-180)
export { createLazyComponent, LoadingFallback } from './performance/index.js';
export type {
  LazyComponentOptions,
  LazyComponentResult,
  LoadingFallbackProps,
} from './performance/index.js';
