/**
 * @crewspace/ui — Design system React components
 *
 * This package provides the Crewspace visual design system:
 * - Tailwind theme preset & CSS custom properties
 * - Base UI components (Button, Input, Card, Badge, Modal, Tooltip, Spinner)
 * - Design token constants for programmatic access
 */

// Components
export {
  Button,
  type ButtonProps,
  type ButtonVariant,
  type ButtonSize,
  Input,
  type InputProps,
  Card,
  CardHeader,
  CardBody,
  type CardProps,
  type CardHeaderProps,
  type CardBodyProps,
  Badge,
  type BadgeProps,
  type BadgeVariant,
  Modal,
  type ModalProps,
  Tooltip,
  type TooltipProps,
  Spinner,
  type SpinnerProps,
  // Canvas (TASK-135, TASK-136)
  WorkflowCanvas,
  type WorkflowCanvasProps,
  WorkflowNode,
  WorkflowEdge,
  CanvasBackground,
  type CanvasBackgroundProps,
  CanvasControls,
  type CanvasControlsProps,
  CanvasMinimap,
  type CanvasMinimapProps,
  NodeShell,
  type NodeShellProps,
  defaultIcons,
  AgentNode,
  TaskNode,
  ToolNode,
  LLMNode,
  type CanvasNodeType,
  type NodeStatus,
  type WorkflowNodeData,
  type EdgeVariant,
  type WorkflowEdgeData,
  type BaseNodeProps,
  type AgentNodeMeta,
  type TaskNodeMeta,
  type ToolNodeMeta,
  type LLMNodeMeta,
  type NodeStyleOverrides,
  Z_INDEX,
  CANVAS_CONFIG,
  // Timeline (TASK-143)
  TimelineChart,
  type TimelineChartProps,
  TimeAxis,
  type TimeAxisProps,
  AgentLane,
  type AgentLaneProps,
  EventBlock,
  type EventBlockProps,
  EventMarker,
  type EventMarkerProps,
  Playhead,
  type PlayheadProps,
  TIMELINE_SIZING,
  EVENT_STYLES,
  isPointEvent,
  type TimelineEventType,
  type LogLevel,
  type TimelineEvent,
  type TimelineAgent,
  type TimelineViewport,
  type TickScale,
  // Log Viewer (TASK-144)
  LogViewer,
  type LogViewerProps,
  LogRow,
  type LogRowProps,
  type LogEntry,
  formatTimestamp,
  tokenizeJson,
  highlightSearch,
  type SyntaxToken,
  type HighlightSegment,
  LOG_SIZING,
  LOG_LEVEL_STYLES,
  LOG_COLORS,
  SYNTAX_COLORS,
  // Dashboard (TASK-151)
  WorkflowStatusBadge,
  type WorkflowStatusBadgeProps,
  WorkflowCard,
  type WorkflowCardProps,
  WorkflowListRow,
  type WorkflowListRowProps,
  SearchBar,
  type SearchBarProps,
  FilterChips,
  type FilterChipsProps,
  type FilterOption,
  ViewToggle,
  type ViewToggleProps,
  DashboardToolbar,
  type DashboardToolbarProps,
  EmptyState,
  type EmptyStateProps,
  WorkflowGrid,
  type WorkflowGridProps,
  WorkflowList,
  type WorkflowListProps,
  DashboardPage,
  type DashboardPageProps,
  type WorkflowStatus,
  type ViewMode,
  type SortField,
  type SortDirection,
  type WorkflowSummary,
  type DashboardFilters,
} from './components/index.js';

// Theme
export { crewspaceTailwindPreset, crewspaceTheme } from './theme/index.js';

// Design tokens (programmatic)
export {
  colors,
  sizing,
  radius,
  typography,
  transitions,
} from './theme/tokens.js';
