/**
 * Crewspace — Code Review Crew Example
 *
 * This example demonstrates how to build a multi-agent code review crew that
 * uses file tools (read, write, list) to perform an automated code review:
 *
 *   1. **Scanner** — lists project files and identifies which ones to review
 *   2. **Reviewer** — reads source files and analyzes code quality, bugs, and style
 *   3. **Reporter** — compiles review findings into a structured review report
 *
 * Key concepts:
 *   - Using built-in file tools (readFile, writeFile, listFiles)
 *   - Multi-step task dependencies (scan → review → report)
 *   - Passing results between agents via dependency context
 *   - Subscribing to crew lifecycle events for progress tracking
 *   - Agents with specialized roles collaborating on a single goal
 *
 * Prerequisites:
 *   npm install @crewspace/core
 *
 * Usage:
 *   npx tsx examples/code-review-crew.ts
 *
 * Note: This example uses a mock LLM provider for demonstration purposes.
 * Replace it with a real provider (OpenAI, Anthropic, Ollama) for production use.
 */

import { Agent, Crew, createFileTools } from '@crewspace/core';
import type { LLMProvider, LLMMessage, LLMResponse } from '@crewspace/core';

// -- Mock LLM provider (replace with createOpenAIProvider() for real use) ----

const mockResponses: Record<string, string> = {
  scan:
    'Scanned project directory and identified the following files for review:\n' +
    '1. src/utils.ts — Utility functions (high priority: shared across modules)\n' +
    '2. src/api.ts — API route handlers (high priority: security-sensitive)\n' +
    '3. src/config.ts — Configuration loader (medium priority)\n' +
    '4. src/index.ts — Entry point (low priority: mostly imports)\n' +
    '\nRecommendation: Focus review on utils.ts and api.ts as they have the most impact.',
  review:
    '## Code Review Findings\n\n' +
    '### src/utils.ts\n' +
    '- **Bug** [Line 42]: Division by zero not guarded in `calculateAverage()`\n' +
    '- **Style** [Line 15]: Magic number `86400` should be a named constant (SECONDS_PER_DAY)\n' +
    '- **Performance** [Line 78]: Array.find() inside a loop creates O(n²) complexity\n\n' +
    '### src/api.ts\n' +
    '- **Security** [Line 23]: User input not sanitized before SQL query\n' +
    '- **Bug** [Line 56]: Missing error handling in async route — uncaught promise rejection\n' +
    '- **Style** [Line 89]: Inconsistent error response format (string vs object)\n\n' +
    '### src/config.ts\n' +
    '- **Style** [Line 5]: Unused import of `path` module\n' +
    '- **Improvement** [Line 30]: Consider using Zod schema for config validation\n\n' +
    'Summary: 2 bugs, 1 security issue, 3 style issues, 1 performance issue, 1 improvement suggestion.',
  report:
    '# Code Review Report\n\n' +
    '## Overview\n' +
    'Automated code review of 4 source files completed successfully.\n\n' +
    '## Severity Summary\n' +
    '| Severity | Count |\n' +
    '|----------|-------|\n' +
    '| 🔴 Critical (Security) | 1 |\n' +
    '| 🟠 High (Bug) | 2 |\n' +
    '| 🟡 Medium (Performance) | 1 |\n' +
    '| 🔵 Low (Style) | 3 |\n' +
    '| 💡 Suggestion | 1 |\n\n' +
    '## Action Items\n' +
    '1. **[CRITICAL]** Sanitize user input in api.ts:23 before SQL query\n' +
    '2. **[HIGH]** Add zero-division guard in utils.ts:42\n' +
    '3. **[HIGH]** Add error handling for async route in api.ts:56\n' +
    '4. **[MEDIUM]** Refactor O(n²) loop in utils.ts:78\n\n' +
    '## Conclusion\n' +
    'The codebase has 1 critical security issue that should be addressed immediately.\n' +
    'Overall code quality is good with minor style improvements needed.\n\n' +
    '---\n' +
    'Generated by Crewspace Code Review Crew',
};

function createReviewMockProvider(): LLMProvider {
  return {
    name: 'review-mock',
    async generateText(messages: readonly LLMMessage[]): Promise<LLMResponse> {
      const lastUserMessage = [...messages].reverse().find((m) => m.role === 'user');
      const content = lastUserMessage?.content?.toLowerCase() ?? '';

      let response = mockResponses['scan'];
      if (content.includes('review') || content.includes('analy') || content.includes('read')) {
        response = mockResponses['review'];
      } else if (
        content.includes('report') ||
        content.includes('compil') ||
        content.includes('write')
      ) {
        response = mockResponses['report'];
      }

      return {
        content: response,
        tokenUsage: {
          promptTokens: messages.length * 40,
          completionTokens: 200,
          totalTokens: messages.length * 40 + 200,
        },
        finishReason: 'stop',
      };
    },
  };
}

// -- Create file tools (scoped to project directory) -------------------------

const fileTools = createFileTools({ basePath: './src' });

// -- Create specialized agents -----------------------------------------------

// 1. Scanner — lists and identifies files for review
const scanner = new Agent({
  id: 'scanner',
  role: 'Code Scanner',
  goal: 'Scan the project directory and identify source files that need code review',
  backstory:
    'You are a meticulous code scanner who examines project structures. ' +
    'You use file listing tools to discover source files and prioritize them ' +
    'based on their importance and risk level for code review.',
  tools: [fileTools.listFiles, fileTools.readFile],
  llmProvider: createReviewMockProvider(),
});

// 2. Reviewer — reads files and identifies issues
const reviewer = new Agent({
  id: 'reviewer',
  role: 'Senior Code Reviewer',
  goal: 'Review source code for bugs, security issues, style problems, and improvement opportunities',
  backstory:
    'You are a senior software engineer with 15 years of experience in code review. ' +
    'You read source files carefully and identify bugs, security vulnerabilities, ' +
    'performance issues, and style inconsistencies. You categorize findings by severity.',
  tools: [fileTools.readFile, fileTools.listFiles],
  llmProvider: createReviewMockProvider(),
});

// 3. Reporter — compiles findings into a structured report
const reporter = new Agent({
  id: 'reporter',
  role: 'Review Report Writer',
  goal: 'Compile code review findings into a clear, actionable report and save it to a file',
  backstory:
    'You are a technical writer who specializes in creating clear, well-structured ' +
    'code review reports. You organize findings by severity, provide action items, ' +
    'and save the final report to a markdown file for the team.',
  tools: [fileTools.writeFile, fileTools.listFiles],
  llmProvider: createReviewMockProvider(),
});

// -- Build the crew with task dependencies -----------------------------------

const reviewCrew = new Crew({
  id: 'code-review-crew',
  name: 'Code Review Crew',
  agents: [scanner, reviewer, reporter],
  tasks: [
    {
      id: 'scan',
      description:
        'Scan the project directory to list all source files. ' +
        'Identify which files should be reviewed and prioritize them by risk level.',
      agentId: 'scanner',
      expectedOutput: 'A prioritized list of source files to review with risk assessment',
    },
    {
      id: 'review',
      description:
        'Review the identified source files for bugs, security issues, ' +
        'performance problems, and style inconsistencies. Read each file ' +
        'and analyze the code thoroughly.',
      agentId: 'reviewer',
      dependencies: ['scan'],
      expectedOutput: 'Detailed review findings categorized by file and severity',
    },
    {
      id: 'write-report',
      description:
        'Compile all review findings into a structured code review report. ' +
        'Include a severity summary table, action items sorted by priority, ' +
        'and an overall conclusion. Save the report to review-report.md.',
      agentId: 'reporter',
      dependencies: ['review'],
      expectedOutput: 'A markdown review report file saved to the output directory',
    },
  ],
});

// -- Subscribe to lifecycle events for progress tracking ---------------------

console.log('=== Crewspace Code Review Crew ===\n');

reviewCrew.on('crew:start', (crewId) => {
  console.log(`🚀 Code review crew "${crewId}" started\n`);
});

reviewCrew.on('crew:task:start', (_crewId, taskId, agentId) => {
  console.log(`▶ Task "${taskId}" → agent "${agentId}"`);
});

reviewCrew.on('crew:task:complete', (_crewId, taskId, result) => {
  const preview = result.output.split('\n')[0].slice(0, 80);
  console.log(`✓ Task "${taskId}" completed (${String(result.duration)}ms)`);
  console.log(`  Preview: ${preview}...`);
  console.log();
});

reviewCrew.on('crew:task:error', (_crewId, taskId, error) => {
  console.error(`✗ Task "${taskId}" failed: ${String(error)}`);
});

reviewCrew.on('crew:complete', (_crewId, runResult) => {
  console.log(`🏁 Code review finished in ${String(runResult.duration)}ms`);
});

// -- Run the code review workflow --------------------------------------------

const result = await reviewCrew.run();

// -- Display results ---------------------------------------------------------

console.log('\n=== Code Review Results ===\n');
console.log(`Success: ${String(result.success)}`);
console.log(`Total duration: ${String(result.duration)}ms`);
console.log(`Tasks completed: ${String(result.taskResults.size)}`);

for (const [taskId, taskResult] of result.taskResults) {
  console.log(`\n--- ${taskId} (agent: ${String(taskResult.agentId)}) ---`);
  console.log(taskResult.output);
  if (taskResult.tokenUsage) {
    console.log(
      `\n[Tokens: ${String(taskResult.tokenUsage.promptTokens)} prompt + ` +
        `${String(taskResult.tokenUsage.completionTokens)} completion = ` +
        `${String(taskResult.tokenUsage.totalTokens)} total]`,
    );
  }
}

// -- Show agent tool summary -------------------------------------------------

console.log('\n=== Agent Tool Summary ===');
for (const agent of [scanner, reviewer, reporter]) {
  const toolNames = Array.from(agent.tools.keys()).join(', ');
  console.log(`${agent.id}: [${toolNames}]`);
}
