/**
 * Crewspace — Research Crew Example (Web + File Tools)
 *
 * This example demonstrates how to build a multi-agent research crew that
 * combines web tools (search, fetch, parse) and file tools (read, write, list)
 * to perform an end-to-end research workflow:
 *
 *   1. **Researcher** — searches the web for information on a topic
 *   2. **Analyst** — fetches and parses web pages to extract key insights
 *   3. **Writer** — compiles findings into a written report saved to disk
 *
 * Key concepts:
 *   - Using built-in web tools (webSearch, fetchUrl, parseHtml)
 *   - Using built-in file tools (writeFile, readFile, listFiles)
 *   - Multi-step task dependencies (search → analyze → write)
 *   - Passing results between agents via dependency context
 *   - Subscribing to crew lifecycle events for progress tracking
 *
 * Prerequisites:
 *   npm install @crewspace/core
 *
 * Usage:
 *   npx tsx examples/research-crew.ts
 *
 * Note: This example uses a mock LLM provider for demonstration purposes.
 * Replace it with a real provider (OpenAI, Anthropic, Ollama) for production use.
 */

import { Agent, Crew, createWebTools, createFileTools } from '@crewspace/core';
import type { LLMProvider, LLMMessage, LLMResponse } from '@crewspace/core';

// -- Mock LLM provider (replace with createOpenAIProvider() for real use) ----

const mockResponses: Record<string, string> = {
  search:
    'Based on web search results, the top AI trends for 2026 are:\n' +
    '1. Autonomous AI agents collaborating in multi-agent systems\n' +
    '2. On-device small language models (SLMs) for edge computing\n' +
    '3. Retrieval-augmented generation (RAG) becoming standard practice\n' +
    '4. AI-powered code generation reaching human parity\n' +
    '5. Multimodal AI combining text, image, audio, and video\n' +
    '\nSources: arxiv.org, techcrunch.com, openai.com',
  analyze:
    '## Key Insights\n\n' +
    '**Multi-Agent Systems** — Frameworks like Crewspace enable teams of AI agents ' +
    'to collaborate on complex tasks, each with specialized roles and tools.\n\n' +
    '**Edge AI** — Small language models under 3B parameters now run on smartphones ' +
    'and IoT devices, enabling offline-first AI applications.\n\n' +
    '**RAG Maturity** — Retrieval-augmented generation has moved from research to ' +
    'production, with vector databases becoming standard infrastructure.\n\n' +
    '**Code Generation** — AI coding assistants now handle full-stack development, ' +
    'reducing boilerplate by 60-80%.\n\n' +
    '**Multimodal AI** — Models that process text, images, and audio simultaneously ' +
    'are unlocking new creative and analytical workflows.',
  report:
    '# AI Trends Report — 2026\n\n' +
    '## Executive Summary\n' +
    'This report identifies five transformative AI trends shaping the technology ' +
    'landscape in 2026, based on analysis of recent research and industry sources.\n\n' +
    '## Key Findings\n' +
    '1. Autonomous agents are now deployed in enterprise workflows\n' +
    '2. Multi-agent collaboration yields 40% better results\n' +
    '3. Tool-augmented LLMs show reduced hallucination\n\n' +
    '## Methodology\n' +
    'Web search and source analysis using Crewspace research crew.\n\n' +
    '---\n' +
    'Generated by Crewspace Research Crew',
};

function createResearchMockProvider(): LLMProvider {
  return {
    name: 'research-mock',
    async generateText(messages: readonly LLMMessage[]): Promise<LLMResponse> {
      const lastUserMessage = [...messages].reverse().find((m) => m.role === 'user');
      const content = lastUserMessage?.content?.toLowerCase() ?? '';

      let response = mockResponses['search'];
      if (content.includes('analy') || content.includes('parse') || content.includes('fetch')) {
        response = mockResponses['analyze'];
      } else if (content.includes('report') || content.includes('write')) {
        response = mockResponses['report'];
      }

      return {
        content: response,
        tokenUsage: {
          promptTokens: messages.length * 50,
          completionTokens: 150,
          totalTokens: messages.length * 50 + 150,
        },
        finishReason: 'stop',
      };
    },
  };
}

// -- Create tools ------------------------------------------------------------

// Web tools: webSearch, fetchUrl, parseHtml
const webTools = createWebTools({ timeoutMs: 10_000 });

// File tools: readFile, writeFile, listFiles (scoped to ./output)
const fileTools = createFileTools({ basePath: './output' });

// -- Create specialized agents -----------------------------------------------

// 1. Researcher — uses web search to find relevant sources
const researcher = new Agent({
  id: 'researcher',
  role: 'Web Research Specialist',
  goal: 'Search the web to find the most relevant and recent information on a given topic',
  backstory:
    'You are an expert researcher with a knack for finding high-quality sources. ' +
    'You use web search tools to discover articles, papers, and reports, then ' +
    'compile a list of key findings with source URLs.',
  tools: [webTools.webSearch, webTools.fetchUrl],
  llmProvider: createResearchMockProvider(),
});

// 2. Analyst — fetches web pages and extracts key insights
const analyst = new Agent({
  id: 'analyst',
  role: 'Content Analyst',
  goal: 'Analyze web content to extract structured insights and key takeaways',
  backstory:
    'You are a skilled data analyst who excels at reading raw web content and ' +
    'distilling it into clear, structured insights. You use parseHtml and readFile ' +
    'tools to access and process web pages.',
  tools: [webTools.parseHtml, fileTools.readFile, fileTools.listFiles],
  llmProvider: createResearchMockProvider(),
});

// 3. Writer — compiles findings into a report and saves it
const writer = new Agent({
  id: 'writer',
  role: 'Technical Report Writer',
  goal: 'Write a clear, well-structured report and save it to a file',
  backstory:
    'You are a professional technical writer who transforms research findings ' +
    'into polished reports. You save your output using file tools so the report ' +
    'can be shared and archived.',
  tools: [fileTools.writeFile, fileTools.listFiles],
  llmProvider: createResearchMockProvider(),
});

// -- Build the crew with task dependencies -----------------------------------

const researchCrew = new Crew({
  id: 'research-crew',
  name: 'AI Research Crew',
  agents: [researcher, analyst, writer],
  tasks: [
    {
      id: 'search',
      description:
        'Search the web for the top AI trends in 2026. ' +
        'Find at least 5 trends with supporting sources.',
      agentId: 'researcher',
      expectedOutput: 'A list of AI trends with brief descriptions and source URLs',
    },
    {
      id: 'analyze',
      description:
        'Analyze and parse the content from the discovered sources. ' +
        'Extract key findings, trends, and supporting data.',
      agentId: 'analyst',
      dependencies: ['search'],
      expectedOutput: 'Structured analysis with key findings and confidence level',
    },
    {
      id: 'write-report',
      description:
        'Write a comprehensive report based on the research and analysis. ' +
        'Include an executive summary, key findings, and methodology. ' +
        'Save the report to report.md using the writeFile tool.',
      agentId: 'writer',
      dependencies: ['analyze'],
      expectedOutput: 'A markdown report file saved to the output directory',
    },
  ],
});

// -- Subscribe to lifecycle events for progress tracking ---------------------

console.log('=== Crewspace Research Crew (Web + File Tools) ===\n');

researchCrew.on('crew:start', (crewId) => {
  console.log(`🚀 Research crew "${crewId}" started\n`);
});

researchCrew.on('crew:task:start', (_crewId, taskId, agentId) => {
  console.log(`▶ Task "${taskId}" → agent "${agentId}"`);
});

researchCrew.on('crew:task:complete', (_crewId, taskId, result) => {
  const preview = result.output.split('\n')[0].slice(0, 80);
  console.log(`✓ Task "${taskId}" completed (${String(result.duration)}ms)`);
  console.log(`  Preview: ${preview}...`);
  console.log();
});

researchCrew.on('crew:task:error', (_crewId, taskId, error) => {
  console.error(`✗ Task "${taskId}" failed: ${String(error)}`);
});

researchCrew.on('crew:complete', (_crewId, runResult) => {
  console.log(`🏁 Crew finished in ${String(runResult.duration)}ms`);
});

// -- Run the research workflow -----------------------------------------------

const result = await researchCrew.run();

// -- Display results ---------------------------------------------------------

console.log('\n=== Research Results ===\n');
console.log(`Success: ${String(result.success)}`);
console.log(`Total duration: ${String(result.duration)}ms`);
console.log(`Tasks completed: ${String(result.taskResults.size)}`);

for (const [taskId, taskResult] of result.taskResults) {
  console.log(`\n--- ${taskId} (agent: ${String(taskResult.agentId)}) ---`);
  console.log(taskResult.output);
  if (taskResult.tokenUsage) {
    console.log(
      `\n[Tokens: ${String(taskResult.tokenUsage.promptTokens)} prompt + ` +
        `${String(taskResult.tokenUsage.completionTokens)} completion = ` +
        `${String(taskResult.tokenUsage.totalTokens)} total]`,
    );
  }
}

// -- Show agent tool registrations -------------------------------------------

console.log('\n=== Agent Tool Summary ===');
for (const agent of [researcher, analyst, writer]) {
  const toolNames = Array.from(agent.tools.keys()).join(', ');
  console.log(`${agent.id}: [${toolNames}]`);
}
