/**
 * Crewspace — Research Crew Example (Web + File Tools)
 *
 * This example demonstrates how to build a multi-agent research crew that
 * combines web tools (search, fetch, parse) and file tools (read, write, list)
 * to perform an end-to-end research workflow:
 *
 *   1. A Web Researcher searches the web for a topic
 *   2. A Content Analyst fetches and parses top sources
 *   3. A Report Writer saves the final report to disk
 *
 * Key concepts:
 *   - Equipping agents with built-in web and file tools
 *   - Multi-step task dependencies (search → analyze → write)
 *   - Combining tool results across agent boundaries
 *   - Lifecycle events for observability
 *
 * Prerequisites:
 *   npm install @crewspace/core
 *
 * Usage:
 *   npx tsx examples/research-crew.ts
 *
 * Note: This example uses a mock LLM provider for demonstration purposes.
 * Replace it with a real provider (OpenAI, Anthropic, Ollama) for production use.
 */

import { Agent, Crew, createWebTools, createFileTools } from '@crewspace/core';
import type { LLMProvider, LLMMessage, LLMResponse, Tool } from '@crewspace/core';

// -- Mock LLM provider (replace with createOpenAIProvider() for real use) ----

const mockResponses: Record<string, string> = {
  search:
    'I searched for "AI agents 2026" and found 3 key sources:\n' +
    '1. "The Rise of Autonomous Agents" — arxiv.org/papers/agents-2026\n' +
    '2. "Multi-Agent Systems in Production" — blog.example.com/multi-agent\n' +
    '3. "Tool-Using LLMs" — research.example.com/tool-llms',
  analyze:
    '## Analysis of AI Agent Trends 2026\n\n' +
    '**Key Finding 1:** Autonomous agents are moving from research to production.\n' +
    '**Key Finding 2:** Multi-agent collaboration outperforms single-agent setups by 40%.\n' +
    '**Key Finding 3:** Tool-using LLMs reduce hallucination rates significantly.\n\n' +
    'Sources reviewed: 3 | Confidence: High',
  report:
    '# AI Agents Research Report — 2026\n\n' +
    '## Executive Summary\n' +
    'AI agents are transitioning from experimental to production-ready systems.\n\n' +
    '## Key Findings\n' +
    '1. Autonomous agents are now deployed in enterprise workflows\n' +
    '2. Multi-agent collaboration yields 40% better results\n' +
    '3. Tool-augmented LLMs show reduced hallucination\n\n' +
    '## Methodology\n' +
    'Web search and source analysis using Crewspace research crew.\n\n' +
    '---\n' +
    'Generated by Crewspace Research Crew',
};

function createResearchMockProvider(): LLMProvider {
  return {
    name: 'research-mock',
    async generateText(messages: readonly LLMMessage[]): Promise<LLMResponse> {
      const userMsg = [...messages].reverse().find((m) => m.role === 'user');
      const content = userMsg?.content?.toLowerCase() ?? '';

      let response = mockResponses['search'];
      if (content.includes('analyze') || content.includes('parse')) {
        response = mockResponses['analyze'];
      } else if (content.includes('report') || content.includes('write')) {
        response = mockResponses['report'];
      }

      return {
        content: response,
        tokenUsage: {
          promptTokens: messages.length * 50,
          completionTokens: 120,
          totalTokens: messages.length * 50 + 120,
        },
        finishReason: 'stop',
      };
    },
  };
}

// -- Set up built-in tools ---------------------------------------------------

// Web tools: webSearch, fetchUrl, parseHtml
const webTools = createWebTools({ timeoutMs: 10_000 });

// File tools: readFile, writeFile, listFiles (scoped to ./output)
const fileTools = createFileTools({ basePath: './output' });

// Helper to collect tools into an array
function toolsArray(...tools: Tool[]): Tool[] {
  return tools;
}

// -- Create specialized agents -----------------------------------------------

// 1. Web Researcher — searches and fetches sources from the web
const webResearcher = new Agent({
  id: 'web-researcher',
  role: 'Web Research Specialist',
  goal: 'Search the web and gather relevant sources on a given topic',
  backstory:
    'An expert at finding authoritative sources using web search and URL fetching. ' +
    'Always retrieves primary sources rather than relying on summaries.',
  tools: toolsArray(webTools.webSearch, webTools.fetchUrl),
  llmProvider: createResearchMockProvider(),
});

// 2. Content Analyst — parses and analyzes the gathered content
const contentAnalyst = new Agent({
  id: 'content-analyst',
  role: 'Content Analyst',
  goal: 'Analyze web content and extract key insights',
  backstory:
    'A meticulous analyst who reads source material carefully, extracts structured ' +
    'insights, and identifies patterns across multiple documents.',
  tools: toolsArray(webTools.parseHtml, fileTools.readFile, fileTools.listFiles),
  llmProvider: createResearchMockProvider(),
});

// 3. Report Writer — writes the final report to a file
const reportWriter = new Agent({
  id: 'report-writer',
  role: 'Technical Report Writer',
  goal: 'Compile research findings into a well-structured report and save to disk',
  backstory:
    'A skilled technical writer who produces clear, well-organized reports ' +
    'with executive summaries, key findings, and methodology sections.',
  tools: toolsArray(fileTools.writeFile, fileTools.listFiles),
  llmProvider: createResearchMockProvider(),
});

// -- Build the research crew -------------------------------------------------

const researchCrew = new Crew({
  id: 'research-crew',
  name: 'AI Research Crew',
  agents: [webResearcher, contentAnalyst, reportWriter],
  tasks: [
    {
      id: 'search-sources',
      description: 'Search the web for "AI agents 2026" and identify the top 3 sources',
      expectedOutput: 'A list of source titles, URLs, and brief descriptions',
      agentId: 'web-researcher',
    },
    {
      id: 'analyze-content',
      description:
        'Analyze and parse the content from the discovered sources. ' +
        'Extract key findings, trends, and supporting data.',
      expectedOutput: 'Structured analysis with key findings and confidence level',
      agentId: 'content-analyst',
      dependencies: ['search-sources'],
    },
    {
      id: 'write-report',
      description:
        'Write a comprehensive research report based on the analysis. ' +
        'Include an executive summary, key findings, and methodology. ' +
        'Save the report to disk.',
      expectedOutput: 'A markdown report file saved to the output directory',
      agentId: 'report-writer',
      dependencies: ['analyze-content'],
    },
  ],
});

// -- Subscribe to lifecycle events (for observability) -----------------------

researchCrew.on('crew:start', (crewId) => {
  console.log(`\n🚀 Research crew "${crewId}" started\n`);
});

researchCrew.on('crew:task:start', (_crewId, taskId, agentId) => {
  console.log(`▶ Task "${taskId}" → agent "${agentId}"`);
});

researchCrew.on('crew:task:complete', (_crewId, taskId, result) => {
  console.log(`✓ Task "${taskId}" completed (${String(result.duration)}ms)`);
  console.log(`  Output preview: ${result.output.slice(0, 80)}...`);
});

researchCrew.on('crew:complete', (_crewId, result) => {
  console.log(`\n🏁 Crew finished in ${String(result.duration)}ms`);
});

// -- Run the research workflow -----------------------------------------------

console.log('=== Crewspace Research Crew (Web + File Tools) ===');

const result = await researchCrew.run();

// -- Display results ---------------------------------------------------------

console.log('\n=== Research Results ===');
console.log(`Success: ${String(result.success)}`);
console.log(`Total duration: ${String(result.duration)}ms`);
console.log(`Tasks completed: ${String(result.taskResults.size)}`);

for (const [taskId, taskResult] of result.taskResults) {
  console.log(`\n--- ${taskId} (agent: ${taskResult.agentId}) ---`);
  console.log(taskResult.output);
  if (taskResult.tokenUsage) {
    console.log(`Tokens: ${String(taskResult.tokenUsage.totalTokens)}`);
  }
}

// -- Show agent tool registrations -------------------------------------------

console.log('\n=== Agent Tool Summary ===');
for (const agent of [webResearcher, contentAnalyst, reportWriter]) {
  const toolNames = Array.from(agent.tools.keys()).join(', ');
  console.log(`${agent.id}: [${toolNames}]`);
}
