/**
 * OAuth Connection Flow – Tailwind Theme Extension
 * Task: TASK-165
 * Screens: provider selection, consent, callback, success, error
 */

export const oauthFlowTheme = {
  colors: {
    'oflow-screen': {
      bg: 'var(--cs-surface-app)',
      overlay: 'rgba(0, 0, 0, 0.6)',
    },
    'oflow-provider': {
      bg: 'var(--cs-surface-card)',
      'bg-hover': 'var(--cs-surface-elevated)',
      border: 'var(--cs-border-default)',
      'border-hover': 'var(--cs-border-strong)',
      'border-selected': 'var(--cs-brand-primary)',
      name: 'var(--cs-text-primary)',
      desc: 'var(--cs-text-secondary)',
    },
    'oflow-consent': {
      bg: 'var(--cs-surface-panel)',
      border: 'var(--cs-border-subtle)',
      'scope-icon': 'var(--cs-brand-primary)',
      'scope-text': 'var(--cs-text-primary)',
      'scope-desc': 'var(--cs-text-tertiary)',
    },
    'oflow-warning': {
      bg: 'rgba(245, 158, 11, 0.1)',
      border: 'var(--cs-status-warning)',
      text: 'var(--cs-status-warning)',
      icon: 'var(--cs-status-warning)',
    },
    'oflow-callback': {
      'spinner-track': 'var(--cs-border-subtle)',
      'spinner-arc': 'var(--cs-brand-primary)',
      message: 'var(--cs-text-secondary)',
      'progress-bg': 'var(--cs-border-subtle)',
      'progress-fill': 'var(--cs-brand-primary)',
    },
    'oflow-success': {
      icon: 'var(--cs-status-success)',
      'icon-bg': 'rgba(16, 185, 129, 0.15)',
      title: 'var(--cs-text-primary)',
      message: 'var(--cs-text-secondary)',
    },
    'oflow-error': {
      icon: 'var(--cs-status-error)',
      'icon-bg': 'rgba(244, 63, 94, 0.15)',
      title: 'var(--cs-text-primary)',
      message: 'var(--cs-text-secondary)',
      retry: 'var(--cs-brand-primary)',
      code: 'var(--cs-text-tertiary)',
    },
    'oflow-btn-primary': {
      bg: 'var(--cs-brand-primary)',
      'bg-hover': '#6366f1',
      'bg-active': '#6d28d9',
      text: '#ffffff',
    },
    'oflow-btn-secondary': {
      bg: 'transparent',
      'bg-hover': 'var(--cs-surface-elevated)',
      text: 'var(--cs-text-secondary)',
      border: 'var(--cs-border-default)',
    },
    'oflow-btn-danger': {
      bg: 'var(--cs-status-error)',
      'bg-hover': '#e11d48',
      text: '#ffffff',
    },
    'oflow-account': {
      bg: 'var(--cs-surface-card)',
      border: 'var(--cs-border-subtle)',
      'avatar-border': 'var(--cs-border-default)',
      name: 'var(--cs-text-primary)',
      email: 'var(--cs-text-tertiary)',
    },
    'oflow-step': {
      active: 'var(--cs-brand-primary)',
      completed: 'var(--cs-status-success)',
      inactive: 'var(--cs-border-subtle)',
      'active-text': '#ffffff',
      'inactive-text': 'var(--cs-text-tertiary)',
      label: 'var(--cs-text-secondary)',
    },
    'oflow-header': {
      title: 'var(--cs-text-primary)',
      subtitle: 'var(--cs-text-secondary)',
    },
  },
  spacing: {
    'oflow-screen-padding': '32px',
    'oflow-screen-max-w': '480px',
    'oflow-screen-min-h': '400px',
    'oflow-header-gap': '16px',
    'oflow-provider-padding': '16px',
    'oflow-provider-gap': '12px',
    'oflow-provider-icon': '40px',
    'oflow-consent-padding': '20px',
    'oflow-consent-gap': '16px',
    'oflow-scope-padding': '12px',
    'oflow-scope-gap': '10px',
    'oflow-scope-icon': '20px',
    'oflow-warning-padding': '12px',
    'oflow-callback-gap': '20px',
    'oflow-spinner-size': '48px',
    'oflow-spinner-width': '3px',
    'oflow-progress-h': '4px',
    'oflow-status-icon': '56px',
    'oflow-checkmark': '28px',
    'oflow-btn-h': '40px',
    'oflow-btn-px': '20px',
    'oflow-btn-gap': '8px',
    'oflow-avatar-size': '36px',
    'oflow-account-gap': '12px',
    'oflow-account-padding': '16px',
    'oflow-step-size': '28px',
    'oflow-step-gap': '8px',
    'oflow-step-line-w': '2px',
  },
  fontSize: {
    'oflow-title': ['1.25rem', { lineHeight: '1.5', fontWeight: '600' }],
    'oflow-subtitle': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
    'oflow-provider-name': ['0.9375rem', { lineHeight: '1.35', fontWeight: '500' }],
    'oflow-provider-desc': ['0.8125rem', { lineHeight: '1.4', fontWeight: '400' }],
    'oflow-scope': ['0.8125rem', { lineHeight: '1.4', fontWeight: '400' }],
    'oflow-warning': ['0.75rem', { lineHeight: '1.5', fontWeight: '500' }],
    'oflow-callback-msg': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
    'oflow-btn': ['0.875rem', { lineHeight: '1.25', fontWeight: '500' }],
    'oflow-account-name': ['0.875rem', { lineHeight: '1.35', fontWeight: '500' }],
    'oflow-account-email': ['0.75rem', { lineHeight: '1.5', fontWeight: '400' }],
    'oflow-step-num': ['0.75rem', { lineHeight: '1.25', fontWeight: '600' }],
    'oflow-step-label': ['0.6875rem', { lineHeight: '1.25', fontWeight: '500' }],
    'oflow-error-code': ['0.75rem', { lineHeight: '1.5', fontWeight: '400' }],
  },
  borderRadius: {
    'oflow-screen': '12px',
    'oflow-provider': '8px',
    'oflow-provider-icon': '6px',
    'oflow-consent': '8px',
    'oflow-warning': '6px',
    'oflow-progress': '9999px',
    'oflow-btn': '8px',
    'oflow-account': '8px',
    'oflow-avatar': '9999px',
  },
  boxShadow: {
    'oflow-screen': '0 24px 48px -12px rgba(0, 0, 0, 0.4)',
    'oflow-provider': '0 1px 3px rgba(0, 0, 0, 0.2)',
    'oflow-provider-hover': '0 4px 12px rgba(0, 0, 0, 0.25)',
    'oflow-btn-primary': '0 1px 3px rgba(124, 58, 237, 0.3)',
  },
  animation: {
    'oflow-screen-enter': 'oauth-screen-enter 300ms cubic-bezier(0.16, 1, 0.3, 1)',
    'oflow-screen-exit': 'oauth-screen-exit 200ms cubic-bezier(0.16, 1, 0.3, 1)',
    'oflow-step-transition': 'oauth-step-transition 250ms cubic-bezier(0.16, 1, 0.3, 1)',
    'oflow-spinner': 'oauth-spinner 800ms linear infinite',
    'oflow-success-bounce': 'oauth-success-bounce 500ms cubic-bezier(0.34, 1.56, 0.64, 1)',
    'oflow-error-shake': 'oauth-error-shake 400ms cubic-bezier(0.65, 0, 0.35, 1)',
    'oflow-progress-fill': 'oauth-progress-fill 2000ms cubic-bezier(0.65, 0, 0.35, 1)',
    'oflow-provider-stagger': 'oauth-provider-stagger 250ms cubic-bezier(0.16, 1, 0.3, 1)',
  },
  keyframes: {
    'oauth-screen-enter': {
      from: { opacity: '0', transform: 'scale(0.95) translateY(8px)' },
      to: { opacity: '1', transform: 'scale(1) translateY(0)' },
    },
    'oauth-screen-exit': {
      from: { opacity: '1', transform: 'scale(1) translateY(0)' },
      to: { opacity: '0', transform: 'scale(0.95) translateY(-8px)' },
    },
    'oauth-step-transition': {
      from: { opacity: '0', transform: 'translateX(16px)' },
      to: { opacity: '1', transform: 'translateX(0)' },
    },
    'oauth-spinner': {
      from: { transform: 'rotate(0deg)' },
      to: { transform: 'rotate(360deg)' },
    },
    'oauth-success-bounce': {
      '0%': { opacity: '0', transform: 'scale(0.5)' },
      '60%': { transform: 'scale(1.12)' },
      '100%': { opacity: '1', transform: 'scale(1)' },
    },
    'oauth-error-shake': {
      '0%, 100%': { transform: 'translateX(0)' },
      '20%, 60%': { transform: 'translateX(-6px)' },
      '40%, 80%': { transform: 'translateX(6px)' },
    },
    'oauth-progress-fill': {
      from: { width: '0%' },
      to: { width: '100%' },
    },
    'oauth-provider-stagger': {
      from: { opacity: '0', transform: 'translateY(8px)' },
      to: { opacity: '1', transform: 'translateY(0)' },
    },
  },
} as const;
